==== WSL

Setup WSL to work on the BAH laptop and allow seemless testing work

===== Recommended WSL tools 

* Nix-Shell

* Docker 

* Kind

* Kubectl

* ZSH 

* OH-My-ZSH

===== Initial Setup and Bug Fixes

Initially WSL will not have the ability to resolve the DNS that your machine has as well as not have the ability to trust the same certificates as the local machine

===== Fix DNS Resolution and correct systemd errors

1. In WSL open /etc/resolv.conf in your favorite text editor.

2. On your windows machine run `Ipconfig /all` and look for your DNS servers under `Wireless LAN adapter Wi-Fi:` or `Wireless LAN adapter Local Area Connection* 1`.

3. Copy the DNS servers into the resolv.conf file like

```

nameserver 8.8.8.8
nameserver 8.8.4.4

```
[start=4]
. Close and save the resolv.conf file

. Open /etc/wsl.conf

. Set generateResolvConf to False and add a boot option for systemd


```

[network]
generateResolvConf = False
[boot]
systemd=true

```
[start=7]
. Finally set the resolv.conf file to not be able to be edited

```bash 
sudo chattr +i /etc/resolv.conf
```


===== Command line ways to complete above task


```bash

cat <<EOF > /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF

cat <<EOF > /etc/wsl.conf
[network]
generateResolvConf = False
[boot]
systemd=true
EOF

```

===== Copy Zscaler Certificate as a trusted certificate in WSL

1. On the Windows Machine open **Manage Computer Certificates**

2. Open the path **Trusted Root Certification Authorities > Certifates**

3. Find **Zscaler Root CA** Right-Click > All Tasks > Export
  * Click **Next**
  * Change Radio to **Base-64 encoded X.509 (.CER)**
  * Set file name to zscaler.cer 
    * Save
  * Click **Next**
  * Click **Finish**

4. Open WSL 

5. Convert CER to CRT

  
```bash
# Copy Certificate to WSL

# /mnt/c is the C: drive on Windows

cp /mnt/c/Path-to-certifcate ~/zscaler.cer

# Convert File

openssl x509 -inform PEM -in ~/zscaler.cer -out ~/zscaler.crt

```
[start=6]

. Add Certificate to CA Certificates

```bash

#Copy Certificate to CA Certicates Folder

sudo cp ~/zscaler.crt /usr/local/share/ca-certificates/zscaler.crt

#Change Permissions of certificate

sudo chmod 644 /usr/local/share/ca-certificates/zscaler.crt

#Update SSL Certificates

sudo update-ca-certificates

```
[start=7]
. Complete (Test if you need to)


===== Use Zscaler Certificate for Kind Cluster

You are able to inject this the same way as you did in WSL but this way is more repeatable for your kind environment

1. DockerFile

```dockerfile

FROM kindest/node:v1.29.2

ADD ./certs/. /usr/local/share/ca-certificates
RUN chmod 644 /usr/local/share/ca-certificates/zscaler.crt
RUN update-ca-certificates

```

[start=2]
. Build Image and Start Cluster

```bash

docker build -t kind .

kind create cluster --image kind:latest

```

